AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  SNSTopicArn:
    Type: String
    Description: The SNS topic ARN from the parent stack.
  ResizeQueueName:
    Type: String
    Description: The SQS queue name for the resize jobs
  ProcessorQueueName:
    Type: String
    Description: The SQS queue name for the metadata processor jobs
  DeadLetterQueueName:
    Type: String
    Description: The SQS queue name for the metadata processor jobs

Resources:
  SQSResizeQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref ResizeQueueName
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 3

  SQSProcessorQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref ProcessorQueueName
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 3

  SQSProcessorQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SQSProcessorQueue
      PolicyDocument:
        Id: AllowIncomingAccess
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref AWS::AccountId
            Action:
              - sqs:SendMessage
              - sqs:ReceiveMessage
            Resource:
              - !GetAtt SQSProcessorQueue.Arn
          - Effect: Allow
            Principal: "*"
            Action:
              - sqs:SendMessage
            Resource:
              - !GetAtt SQSProcessorQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref SNSTopicArn

  SQSResizeQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SQSResizeQueue
      PolicyDocument:
        Id: AllowIncomingAccess
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref AWS::AccountId
            Action:
              - sqs:SendMessage
              - sqs:ReceiveMessage
            Resource:
              - !GetAtt SQSResizeQueue.Arn
          - Effect: Allow
            Principal: "*"
            Action:
              - sqs:SendMessage
            Resource:
              - !GetAtt SQSResizeQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref SNSTopicArn

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref DeadLetterQueueName
      VisibilityTimeout: 60

  SNSSubscriptionForResizeQueue:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SNSTopicArn
      Endpoint: !GetAtt SQSResizeQueue.Arn
      Protocol: sqs
      RawMessageDelivery: true

  SNSSubscriptionForProcessorQueue:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SNSTopicArn
      Endpoint: !GetAtt SQSProcessorQueue.Arn
      Protocol: sqs
      RawMessageDelivery: true

Outputs:
  SQSProcessorQueueArn:
    Description: The SQS processor queue ARN
    Value: !GetAtt SQSProcessorQueue.Arn
  SQSResizeQueueArn:
    Description: The SQS resize queue ARN
    Value: !GetAtt SQSResizeQueue.Arn
